name: Day 15 CD Pipeline

on:
  push:
    paths:
      - 'day15-cd/**' # Only run when we touch the Day 15 App

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Get the Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Configure AWS Credentials (using your Secrets)
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # 3. Login to ECR (This action handles the complex password logic for us)
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # 4. Build and Push
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: devops-bootcamp  # MUST MATCH YOUR AWS REPO NAME
        IMAGE_TAG: latest
      run: |
        cd day15-cd
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG