name: Deploy to AWS ECR

on:
  push:
    paths:
      - 'day15-cd/**'  # Only trigger when we change Day 15 files

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Login to AWS ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1

    # 3. Build, Tag, and Push Image
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: devops-bootcamp # Must match your AWS Repo Name
        IMAGE_TAG: latest
      run: |
        cd day15-cd
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG